---
apiVersion: v1
kind: Namespace
metadata:
  name: test-deploy
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-deploy
  name: test-deploy
  namespace: test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: test-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: test-volume
        configMap:
          name: test-cm
status: {}
