apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: datadog-cluster-agent
  namespace: datadog-demo
  labels:
    agent.datadoghq.com/name: datadog
spec:
  selector:
    matchLabels:
      agent.datadoghq.com/name: datadog
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        agent.datadoghq.com/name: datadog
