apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    kustomize.config.k8s.io/behavior: "merge"
    reloader.stakater.com/auto: "true"
  name: datadog-agent
  namespace: datadog-demo
spec:
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
