apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: datadog-agent
  namespace: datadog-demo
  labels:
    app: datadog
spec:
  selector:
    matchLabels:
      app: datadog
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app: datadog
