#source: https://kubectl.docs.kubernetes.io/guides/config_management/components/
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - datadog-patches.yaml
  - datadog-dply-patch.yaml
patches:
- path: ./datadog-patches.yaml
  target:
    kind: DaemonSet
    namespace: datadog-demo
- path: ./datadog-dply-patch.yaml
  target:
    kind: Deployment
    namespace: datadog-demo