apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-reloader
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-reloader
  template:
    metadata:
      labels:
        app: demo-reloader
    spec:
      serviceAccountName: demo-sa
      containers:
        - name: nginx
          image: nginx
          envFrom:
            - configMapRef:
                name: welcomecm
          env:
            - name: REQUESTS_CA_BUNDLE
              value: "/certs/allCAbundle.pem"
            - name: SSL_CERT_FILE
              value: "/certs/allCAbundle.pem"
          volumeMounts:
            - name: configmap-volume
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: configmap-volume
          configMap:
            name: welcomecm
            items:
              - key: "welcome.html"
                path: "welcome.html"
              - key: "welcome.html"
                path: "index.html"
