namespace: demo
resources:
  - namespace.yaml
  - deployment.yaml
  - sa.yaml
  - cronjob-example.yaml
  - secret.yaml

# This file is used to generate ConfigMaps and Secrets for the reloader-fidget-app.
configMapGenerator:
  - name: welcomecm
    files:
      - welcome.html
      - hello.html
generatorOptions:
  disableNameSuffixHash: true
#patchesStrategicMerge:
#  - patch.yaml
