---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rotate-secret-shell-script
  namespace: demo
data:
  modify-webcontent.sh: |
    apk --no-cache add curl jq

    # Kubernetes API
    APISERVER=https://kubernetes.default.svc
    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
    NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
    TOKEN=$(cat ${SERVICEACCOUNT}/token)
    CACERT=${SERVICEACCOUNT}/ca.crt

    # ConfigMap
    CM_NAME=webcontent-cm

    export cm_response=$(curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps/${CM_NAME})
    #echo $cm_response

    cm_code=$(echo $cm_response | jq -r ".code")

    echo '$cm_response' keys ...:
    echo $cm_response | jq -r '. | keys'

    echo '$cm_response' .data START...:
    cm_data=$(echo $cm_response | jq -r '.data')
    #echo $cm_data
    echo '$cm_response' .data END...:

    echo '$cm_response'.data keys START...:
    echo $cm_data | jq -r '. | keys'
    echo '$cm_response'.data keys END...:

    echo '$cm_hello' .data.["hello.html"] START...:
    cm_hello=$(echo $cm_data | jq -r '.["hello.html"]')
    echo $cm_hello
    echo '$cm_hello' .data.["hello.html"] END...:

    echo '$cm_welcome' .data.["welcome.html"] START...:
    cm_welcome=$(echo $cm_data | jq -r '.["welcome.html"]')
    echo $cm_welcome
    echo '$cm_welcome' .data.["welcome.html"] END...:

    cm_payload='{"metadata": {"name": "'${CM_NAME}'", "namespace": "'${NAMESPACE}'"}, "data": {"cm_response": "'${cm_response}'"}}'

    #echo $cm_payload

    if [ $cm_code -eq 404 ]; then
      #echo Creating ConfigMap: ${CM_NAME}
      curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X POST ${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps \
      -H "Content-Type: application/json" \
      -d "${cm_payload}"
    else
      # Update ConfigMap with encoded session token
      #echo Updating ConfigMap: ${CM_NAME}
      #echo ${CM_NAME} ... "${cm_payload}"
      #curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X #PUT ${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps/${CM_NAME} \
      #-H "Content-Type: application/json" \
      #-d "${cm_payload}"
    fi
