apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:mKcFWLJExN+DWw4SKIQIJs5poAQYcrmkpHKrsLdTqh6Z+FWmnX4C1hIyDPc=,iv:OwVf0+gnJhyEI7dojMICbw/drqrwC+OtOjBfr7W57Gk=,tag:unTLvyQb5jhUx9aT7on/cg==,type:str]
    app-key: ENC[AES256_GCM,data:8lxGmCJ7FERDaOX7mVn0hH6I1SISrxtqbkW0Jty3JBaMSw6LpAYJEUSsq6xOAfCRb39VaCqBmSU=,iv:4J8+y4f3mtnyymYsrvbeIaGfVaZt2B8RznaqeghVNbQ=,tag:fVidozcw0KYkK9TY+KvPfw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: datadog-secret
    namespace: datadog-demo
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-05T22:35:59Z"
    mac: ENC[AES256_GCM,data:jxrwRYakqhPdibKrTmKKbHYeVjSVB43nkfzdAftnjI1gPKUR5ZR2Z4xagp+qWHY5CbPulsntc6lIlhlXlFYzE8wFbtxlsEnnQ3zy1NjjeIB6SRUlpeFgBOKDlNbzBmyF2iRBcC/zgt3p1uERrfJ7MTfLcnh0ebyNeVScblERh+g=,iv:1KNCPpZcPEKsFOp7gBu2K/jPhpBDnM1ICD10Fgr1mhg=,tag:TgClqr9WBXVs7Yl6aD9yEA==,type:str]
    pgp:
        - created_at: "2025-08-05T22:35:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxlAqXggcV6GAQ//WWXgZfRKY9oxOyI3o+yhO56qW5+Pb4pftjtcl6RYwmDn
            xHjZTIykdW0iviLiWqI6MYmd2ip7NOpbaVbXl708Yn4O/QRe5btZNBW0aD0PZrAP
            mBkoapsGDvi0z/Kq15/Ba12bdTTSFeLztyBxv95ChxQfwCnlO5hh6/wV/jVI63Sh
            M5UcyZ4wznLEpGxUAO4TJs5HlIMJIHQatcwRNJ5VL9AbzHtj+loHFDikl2EoqtXc
            +6ops5GFckE3K16LP/I6pwo2xdiCzoV0V/d4Oep/9BrjTeOhh58oD5uxUR1OWCav
            A8yXEjwAdPQ7C6MP6SMa8DXUXqbKi2M/0hzd05dya0qSwhToTf/ZPbNpRG5lAe2a
            rUMUzu/DC/4zBH6npIcOoboimrrt3DVbMIIyHKoyPoXbK9nrdv6WmqRycdTEnELH
            z6+bf5ktMpIpS28/X6yFDb8YH4bH5hbCbU+9V6K4UlETC3VvMWakFFW3kPsQ63VV
            lw87s31BDXgtxNNLpZXrTYO9OBv/LmKO3MxibF7jCUaDBRXtMYq+mM3WnWZnatW8
            KG/ZWY1Ydg2CvTjToX+svtvBDWge0c3sf72yrUaU5s1hVsXafER3JmZufx576BMv
            svqsLrNX+2chRxNPWrE6PUDeUkSIW2VcJli+VryG1Gp5JMkSbPsKELOhvwIKhUzS
            XgESip2z2yPYt5JhABB/H222BXEcSTPhvsflhpL5EOtTOZuk5yNU3CDwoFje1KY2
            0dnBqNqsEYEZz8hbiCzg/V7ELG/G/M+V/2qHqtLZIyNzyjIaXGa4oW/2HlTRBOw=
            =M/nP
            -----END PGP MESSAGE-----
          fp: 0430EEEF3BB9BEF6CB0FDA71D3E439478CA2B1BF
    encrypted_regex: (?i)(^data|api-key|app-key)$
    version: 3.9.0
