# source: https://docs.datadoghq.com/opentelemetry/setup/ddot_collector/install/?tab=datadogoperator
#usage: kubectl apply -f ./datadog-demo/datadog-agent.yaml
#       kubectl delete -f ./datadog-demo/datadog-agent.yaml

kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
  namespace: "ij-datadog-demo"
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  global:
    clusterName: "ij-demo-cluster"
    site: "datadoghq.com"
    host: "localhost"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    tags:
      - "env:rie"
  override:
    clusterAgent:
      containers:
        cluster-agent:
          env:
            - name: "DD_ADMISSION_CONTROLLER_ADD_AKS_SELECTORS"
              value: "true"
  # Enable Features
  features:
    otelCollector:
      enabled: true
      ports:
        - containerPort: 4317
          hostPort: 4317
          name: otel-grpc
        - containerPort: 4318
          hostPort: 4318
          name: otel-http
      conf:
        configMap:
          name: otel-agent-config-map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config-map
  namespace: ij-datadog-demo
data:
  # must be named otel-config.yaml
  otel-config.yaml: |-
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "datadog-agent"
              scrape_interval: 10s
              static_configs:
                - targets:
                    - 0.0.0.0:8888
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug:
        verbosity: detailed
      datadog:
        api:
          key: ${env:DD_API_KEY}
          site: ${env:DD_SITE}
    processors:
      infraattributes:
        cardinality: 2
      batch:
        timeout: 10s
    connectors:
      datadog/connector:
        traces:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [infraattributes, batch]
          exporters: [debug, datadog, datadog/connector]
        metrics:
          receivers: [otlp, datadog/connector, prometheus]
          processors: [infraattributes, batch]
          exporters: [debug, datadog]
        logs:
          receivers: [otlp]
          processors: [infraattributes, batch]
          exporters: [debug, datadog]
---
apiVersion: v1
kind: Namespace
metadata:
  name: "ij-datadog-demo"
...