apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:3lWCGGlXHbA9PPOt0HAgwnlbAZLiVlqVu6bDEhwZdkbTrlUQbGA+j6lmLMs=,iv:GHpzss7G9EOiMbfsTdUtLB2TX76whNEYbpkDG12/uFo=,tag:A8cOpZu5lnxlDSxYydXhNQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: datadog-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-14T20:50:36Z"
    mac: ENC[AES256_GCM,data:c1ucaHnOB1mWSt/2LBEP++mBmjzNBVbK960+fbZ3w89UN2w4yYkyBpr1qz8F4nhbf+r7FFrAjxhQJH+Asp7AT9F5tSm6w+E3FiSA2IArfLDldwGBr9nZX8eJSQI5hr16DGbLfqAjTfK5W2YqxNrYOmMVEkZAn4MZqNwDFjishxY=,iv:X+2A8TvbKUssXbM5l5wJNQEPkE+CF0dItSgK3+MlwQo=,tag:q2GuqY6qITo9WFDIe0J/SA==,type:str]
    pgp:
        - created_at: "2025-07-14T20:50:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxlAqXggcV6GAQ//Un1qYFE17sVdxRZN9kISvHrWPtNfyZO6Kzck3b2cX7MM
            DQKXV6aPlkP23GNCA7IuyG2Nujaib0PGKzrVE4P7z5Y8qnWuLyoDAAMG66yI4xVb
            KazDW61LQ1DnwgAy03/F/1k8aRRLF66AhMpf4nMwPemiEkUSBtGw4/lxGdlQdrnl
            6Px8tK4DKnAnYzEjYZXSFZdNMsoNvqCGDzuGEUNDnB+Tq6qlxDQMxRDwHelHziZP
            iquixIRyIoMGLXdWYRKeyI4iBaHHQe70/K2R/+qiHYxpdxPSaJuas0+sNNjYWpOb
            VhVeBw15sf+v/RmVkln2uisWevZPldw76+J5/fdsOrwiPGs5Dh2AjoSiFRX1IwBy
            y2Ged+N6K2H4wvNpAqBsurZTylUrFkdzyEwtWsdtrJmPnpJFaM8HnJALh49UfHtY
            CAuFfpuHWORBqxwnKLxZkxruHapiFMaYNoyLJk8QwQuvQ13uuaC0ouFc8nRhHIJy
            myEWjek4o2cZXZS41wx+V9Flvm15LFD0FiTWPWcrFxein7gYbeOwkhTDgARzo1LX
            bn9G+FOoXK/oN95xlo2X/nticE7qR958WQ8w/Hv2tTD1qz1eoKCeM0ISgZ3AK9k8
            mXgG9x4fBN1qdFVEecYOa4ZAVVBSKaJhxbsis2Vwdp9d39REubY46/2BckfKVX/S
            XgET7uXSrHuT0FOMVHNqhigpQaXNjCVUOaNkShnELMhEbOkW7DAGjAnMWrSjc27Z
            5uEBbpJ44ib2+cDdJ8tpnOsS2H3EdgXP5z0Ap120H3g2zaZTBaY0MmVR2s+uwQ0=
            =wZXl
            -----END PGP MESSAGE-----
          fp: 0430EEEF3BB9BEF6CB0FDA71D3E439478CA2B1BF
    encrypted_regex: (?i)(^data|api-key|app-key)$
    version: 3.9.0
