apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:7I2C01uZKW1yxEbuSWfm0sUNtBOxg3svql2lH//62Pizc16UijeAW7KvMWE=,iv:1a4SN1fGh8ikKj9aXlPcHIdWKbv5M+z+uf4POWDe3ow=,tag:T8+uOc2gkzKJOk4z5mKbig==,type:str]
    app-key: ENC[AES256_GCM,data:jMXe3gHnbUUIykeAjntm7i8Kl9NbVGMgAbqlvpqizTHvVhHpbgrG0+jKH2Jadi7/+vaPd1VrKo8=,iv:GkvfvME7qwWCjb7Xi4vpYknDGCWPn22YPgv5/YGSdwc=,tag:5L4r7GEIyizlc0ZtZ918LA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: datadog-secret
    namespace: datadog-demo
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-06T16:31:37Z"
    mac: ENC[AES256_GCM,data:m/9ARVIdSJytxt8irOXL+TMR3QhOl+Lx8ZBj2AdBhem4Tz5HFyjjng6uren+FSdIsuy5arZGhBb8d5MpW/WVrPGPvE7RF+JYFrbmFXlrVew1nQhlszoDIFZ5ZscUo5IhZ6Q2Se5AnGlf5EKwTim5VtIJ/do7eHoXXhGyIKsXcLY=,iv:o+t6hty9kLpcK3Rq5tE/p+ULciFx81+F6ghHLHPkaow=,tag:x1K2Qw+XNHg8Pv3kk5404w==,type:str]
    pgp:
        - created_at: "2025-08-06T16:31:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxlAqXggcV6GAQ/+Nx4Imns890yLNUpDshdyKTyJ4gJdhC+/kui9pWma/gD4
            L4p4btHSEi3LMZ316+HcoCx8ZRgpV87jlDGSKbwJy96NePTPxdCDQhQ2T/zRWxlS
            A/tjew0mHjB5nM7Dm1LfdAWhd2nHVIpWtNFzAcOTyCblT5GSsnRWSKmp4qy2DbB/
            W0WhyOKhDSA64woFMmZsWjL0BMJE/HdwulzTvYInR1Kf114v+d1FoErOeSZ9rcn+
            D77QAT9xLfyd9+Fg8ZcRDMJBIKdctxE7LE3PUnxiFTQ49fGTNsXJCUhgfhErBfjm
            SGJkDHILjetlkvKts/clVS8u6/95dcmzFLPWUwIZlRrCuDvoebnTK18fMFU7rOGd
            s1u7VK35o0OiYE/YhW5+Vgqg+KdUt7unscNfSn/hrbD63x6qdZW7e1+0xt0uzbZk
            fQ5CnI8oFc0F/t/x9aB0wkFCb4BuqSviX+zmxiYRtrE+C10k9wiJ31kub9wmUPEu
            EeVbG2/0S9BzZ0vpB4OxffFp8CPt+uoLjHtlWmQ8hT5jgVR4srlFYtiCmhcar9Z8
            e8k/iPj1r5kitddX0RYiphqx/r2sVtelxbiigZAPupizj61+lMGz0WlF9UQyRZ5n
            Sj+PmjfshNBTuF7Ie5yP9No3Mo+zw3Eu2RtzP91jGN1jQdEXyTP4zGjqYMNSna7S
            UQFFj7ebTSdmCQzJRI1fzmPoEQcCALdKgAdO3VRM+MJLnjy0G0pR/pgAPyZVslVD
            1aFYr56dlJRCdgyOyKanqMeP4HRevtuFKYA/VraOs3hwcA==
            =+Vik
            -----END PGP MESSAGE-----
          fp: 0430EEEF3BB9BEF6CB0FDA71D3E439478CA2B1BF
    encrypted_regex: (?i)(^data|api-key|app-key)$
    version: 3.9.0
