---
apiVersion: batch/v1
kind: Job
metadata:
  name: get-token-job
  namespace: datadog-demo
spec:
  template:
    spec:
      containers:
        - image: alpine
          imagePullPolicy: IfNotPresent
          name: get-token-job
          envFrom:
            - secretRef:
                name: datadog-secret
          command:
            - /bin/sh
            - -c
            - /shared/get-secret.sh
          volumeMounts:
            - name: script-volume
              mountPath: "/shared/get-secret.sh"
              subPath: get-secret.sh
      volumes:
        - name: script-volume
          configMap:
            name: rotate-secret-shell-script
            defaultMode: 0777
      restartPolicy: Never
