apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  namespace: datadog-demo
  name: datadog-agent
spec:
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
