apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:5O4Hm7AxB3dn+2FF1gDao+4e0UUu4f63JClPTmqjbwOn0OJaCNDChvifeK90Vbfyib5yrg==,iv:QYH1y5+8RsIJFsqhtYq3iB7t7ElNFKS0N8PtkMBpfD4=,tag:YiVQz2Plka5tahDDO3GguQ==,type:str]
    app-key: ENC[AES256_GCM,data:P+MVDXRPf5+aSQPJy6Z5ghiBzkcGoQ4HMJpyyXUtGOFKRPbUj2qs7ECZY91RB87TEgz5w3XmRX4=,iv:q55wuDCjiSHEeaUU8jaeFsl1IGxHo4klbE2uje4iM6s=,tag:jkoIkMxGUAIw5Q18I6aNQA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: datadog-secret
    namespace: datadog-demo
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-05T23:33:32Z"
    mac: ENC[AES256_GCM,data:IDNloLhX5aLqQ/hFbEO7Xl+UE25nRIwagpsDVGCArS8X4mpbciQA8v4xcy3TuzUY/aKrlmvQnIqmys85rFLLWohUKF1VU9u+0Z1qBlU4RYyHQqjSyuCK7GTgpSy5jyv2r+e6VrubiQAI2NMgD8LBJUNcXNSU3oYkoSID/vvMOx0=,iv:ex3MdL8nOG2EzE5Y9JGFe0OawohCjLS5zO4TK/M3O1g=,tag:Nl3j946b03yYdEBYangjKw==,type:str]
    pgp:
        - created_at: "2025-08-05T23:33:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxlAqXggcV6GAQ/9EKU13Iy+ijgPtf5jb5D/ygML1UZf2xxp/slrNQ87TKOG
            sbPO75d139SUtuKVEpVsdrQrss6kreyP1tiZPcjUFMmC5i2Qpg8X7xQJiGOGRjXm
            E68JWlGhr0W+jPCeZxNrm80cusYmWJ+rbKqQ5lP3gVFqfSHm2qWFR466ZLsptWbp
            7u7jfWRAsGZYz4IeFI8e1NpD4T3jwTfs1iYIkxYdElou/FW2QyKeA9VMpomffq8y
            l02SBRy7VP3DnCNRGA/4Vqe06JEhLD0cy/7XGfOMmaIo9u7UOzHQ17ceYYYgfk4K
            7W0RxA6cNqZY7zS5vwR5tAFb+AVTeEHCEPghNcdskliMGoF3/m33KKz+Xvftp9bk
            8Kb85fzzrSmFnddn/KnGF+og+1bNhX0asCF9lnaz73XVGsxPGTWgglVf3aO0dqP8
            WI1DoVPxU4IDjebL6hAEy70W2MlZYg5VEkt84R2g59pI5guNpgDfI55LXdjPdBhh
            muGLsAcay2jxHMZKUvdYj6lR/EQGqQEYeJ8SlKjB2YXVJ6JmbFO2J8DssJftTs5J
            HIwSIu+ga0/l2qIVl0v7fO6MAOAdiQGYK0Xq2AFTDwaFGt3jSw6vM78wopevXQVQ
            lMF3SLMhjdLz2yJkz81mac+YlGdaTT1m4xKZV8/g0j5zrLVTiZehPABOScs2JlLS
            XgE4c0Dh/24SWVuwGtlG+QVEtNQ0xDmjyCEvMc4Ky8ny8zeFKxFtGMgPlJ/N75ZA
            YLvAuDwfau/MeqDzIa3+CxUSjDdGQBLs9r7WveUn5yKChJqIf+gOrgBMGKdviK8=
            =er5u
            -----END PGP MESSAGE-----
          fp: 0430EEEF3BB9BEF6CB0FDA71D3E439478CA2B1BF
    encrypted_regex: (?i)(^data|api-key|app-key)$
    version: 3.9.0
