apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
  namespace: datadog-demo
spec:
  #selector:
    #matchLabels:
      #reloader.stakater.com/auto: "true"
  template:
    metadata:
      #labels:
        #reloader.stakater.com/auto: "true"
      annotations:
        reloader.stakater.com/auto: "true"
