apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:E/B/Pcssu7yiwtwylQQXUW9yjshHfuOqZdLV6CKJz+SFQ339mh3HGSrcbKf0bdszSHh3cw==,iv:KK9Qvxa8S1uOibfVIxSkaEmCfiHEhjr16xymH6//EsI=,tag:NU9KWlcEudt1HXC1+Q3szw==,type:str]
    app-key: ENC[AES256_GCM,data:Jg77VASxeXIZzPSMoB+85ZEvw1C+o+NT9UsNbkO0FIqZgtDz2B9xaJulXBzKpT70yJSeFJSL1Dw=,iv:eIKmu042+W0/WoHWLgIhe+ATPVbCEZrKcfmcvEbV6Ig=,tag:D+Y1BW2O26+4CECQ3biXOg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: datadog-secret
    namespace: datadog-demo
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-06T16:32:27Z"
    mac: ENC[AES256_GCM,data:cr2MbXrjl/YiKYmbc5kEftYk76uvx7PHtx/DkbT+Q7ynKEYVvCpowue2AuQh/l0GJoerCPLW56m8CFH4Bd4fHAXGhpCfJuAuaRfy4vFKq2/v0nAaW5yX7KRoUQBRwat+rvZPM7WKVnX9WHmNeMZLdQ/tAOSFCiJLqKO/u0QhWlo=,iv:hhMUbEn4Hvvs639ujhuv2X0FhXbGk4PPF9vqsUZNOUc=,tag:rwE8scMSwRR+9CYstPHgpw==,type:str]
    pgp:
        - created_at: "2025-08-06T16:32:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxlAqXggcV6GAQ//eTq57gSdC9UpiVQxNg1zYuWV8ZtBHzyeOdoohpjHXwkF
            pKNSrOuCb7bG8461DhalYvmQvYieemSQ0snBA4Ax4DRNQ17+/YL0A/c3+98z+xxf
            p6wXHolj0sj2fh9U3Ise6MeYdh4L+xfOba6SIRIncvAo8cgvWB3vHxEA4TAtsHQm
            PeMyjG34+QZBaozIzDU0QD46VrpMHZQk/PTHqLgXUtm2SttTInj8tdewNxvyyvUx
            y1FQQcOLQiUy3LqGSdBgrPz7pExM4eqCnXfGsHVxWZPJ8LQo0FS9UxzFTo8RaaVY
            MUmYzoNdZ5SPZC4NM9U7Xfz33KB4EQD61BWo6PP7yfc/QJWlvmSvrUodXmfs+4f6
            I91jV5OMR+VMNVL2kBr7j/dlnoprxD2ye8X4yD3mIZARPY7RGiSyLHRQsgXUTGMb
            /zVXTc/+SB8MZ1lJSthwaFX8bRbDeSIg84vWb7zfQ0Bng52DO6DWRMHsVD7AJ5+8
            uwmsdRId4LHld+jXWnI3WhntPkktJb2Wa0lDK698ZyvS7Q8BpgdGZGU5TYfDB/Vb
            e5OCcDSgLa+nAiBz8a5aVqhRXywxXGD4GN5FKH508AHrduyZqJtbwjpnPZM5+fRq
            le1KXiG3GkwuxIuKCuTZl2vO4ODIc8eBmA0lwB6TMgi+aM5sxml4NlcEDUzfo3PS
            XgF4PtNc+5rmtzo+EjGxoGvWu99biz7mva0VC4mry40J5ZMUdQk2ZSGNQGLs8vid
            /3LY3VVgqfZOtDfuCsMtA8Wipcyu9hg4PBdpa3I7DojCq1SD994AujfxedthyoI=
            =04wu
            -----END PGP MESSAGE-----
          fp: 0430EEEF3BB9BEF6CB0FDA71D3E439478CA2B1BF
    encrypted_regex: (?i)(^data|api-key|app-key)$
    version: 3.9.0
