apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-cluster-agent
  namespace: datadog-demo
spec:
  selector:
    matchLabels:
      agent.datadoghq.com/component: cluster-agent
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        agent.datadoghq.com/component: cluster-agent
