apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:a2o1vXmJnIuH4vsz4y1gGr7qmxmB/KdWSxqN7YX2TCG0L4LQTkx8kE50Qhk=,iv:pQI2doehMwimgRP01X7JcpYlj4SFHlzeIOJQ2zPR/Bo=,tag:iagGSHgSKQCsr2f1S3jDEA==,type:str]
    app-key: ENC[AES256_GCM,data:kmW9ZqeYlqg2xD3K+0DwbdDk10wQEfY2s2TW0oFB++wCN1WhFhhGV9vzOCywxNUe2jJ/1ZNuD0M=,iv:Nh4YmHuIcEE8HPFjWGzXGLA40dawqO7sHbcJQir9Sa4=,tag:yCVfZb46TxbYojc3koflEA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: datadog-secret
    namespace: datadog-demo
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-30T00:16:33Z"
    mac: ENC[AES256_GCM,data:HZIU/+TH19rfFURY6Nmk1vfu0lzXEm7l4uDx5s6WVAD7j2heqY8z9j95J0el6qNIBWKudsA4LQZ01rsdzfZfB7P+mTbzOWhPhFOxDvd/fSYLBTADIS3rMmO1Dg8A9EJlN3n55ev5qyNQsXsARtImX1sY5ozrFeel41BxEEC8n9Y=,iv:KNOtkfuCfpK/jgGEjTAR0DrLSZ9CJzhilNYojA1eFqE=,tag:p7SoRzy8L4NiWWmSUKrdEA==,type:str]
    pgp:
        - created_at: "2025-07-30T00:16:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxlAqXggcV6GAQ/+PdU+6REM5p2l8jdRFMC+EHFyc1jv8PQPuLAGu5/eddvU
            f5qHDLUNdOPl5voXHuqpDpmtMd7/tgV9Do+xiWN8e3hQey8tR68qgRY3Ow7btJZG
            Clh7si+wgk2RhKdIYQ61pXuAwp2M3hFq0alO2eOPzNa2CP6rkpHO+zkMw+KibiZg
            Z+qqZLa+cdLt/T9qpMGGrCS61c31dxXvGLEkuy1qUuy/4tnQdSRQDiV8867Z8JG3
            dZHTU8+L852XWxnLxC4ypKFsMVYE2RTa2mRUYbmMPSszixqjS0Gc+aG7tsszioc5
            AU7Gr9HZVIFnPGtDalGhU0pZAHaogxrNT8b2lUHyahEjMva94Y8B+mky01Jod0OJ
            Rd04+Un4oT3cTn6ySNyqoxzP6N9s72nWdJwvlhpcUpXoV+K69n+DWkih5kbmrAm0
            7emJXgQ95nMknOZJ+wIf/q5jXDJ9jWQLxJ8sK3I2Ie0/b/S5ct3uWynDNccmLBjm
            TShGpEbstvlErC5L7639SM0Vn2pyldRFeqR2BUP3tUz4KnMUymhRxfeKPTPtJROG
            VPxBS0oHqqRbflubxz3spwkuKkTe9WqQemprM26ONvgWyoSHgSi384CuuIsohq2W
            OLKidJNvtIlDkr1zdt1N9e0srJ1uIEaWLOMnj0Bqn2/wnUOBcuu1ek1S1BmHt1/S
            XgG8/DeqJupgGuaVpKADKV4V3r/uB7fUNs81rSKxSEQrx4ZvYvyn8BY7dV3FqcaZ
            5HCAEF+SwpRiaAP52c3kM3QD75f/adCRGdo/wpw9OgoiUcOg/ZLJGh30U/hfM7g=
            =RCSa
            -----END PGP MESSAGE-----
          fp: 0430EEEF3BB9BEF6CB0FDA71D3E439478CA2B1BF
    encrypted_regex: (?i)(^data|api-key|app-key)$
    version: 3.9.0
