apiVersion: v1
data:
    api-key: NTYxNGQzNjItYjU1Mi00NWY1LWJiMzMtMGFmMTM5NjljZTViCg==
    app-key: ZGNkYjQ4NWUtYTVmMC00ODM3LThkYTAtNjc4ZTEyOTFmY2Q4Cg==
kind: Secret
metadata:
    creationTimestamp: null
    name: datadog-secret
    namespace: datadog-demo
type: Opaque
