---
#source: https://scm.starbucks.com/retail-infrastructure-engineering/taas-flux/blob/main/archive/terraform/base/tf-retail-network/script.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rotate-secret-shell-script
  namespace: datadog-demo
data:
  get-token.sh: |
    apk --no-cache add curl jq

    # Kubernetes API
    APISERVER=https://kubernetes.default.svc
    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
    NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
    TOKEN=$(cat ${SERVICEACCOUNT}/token)
    CACERT=${SERVICEACCOUNT}/ca.crt
    # Datadog api-key & app-key
    SECRET_NAME=datadog-secret

    # Retrieve secret from Kubernetes
    response=$(curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/namespaces/${NAMESPACE}/secrets/${SECRET_NAME})
    secret_response=$(echo $response | jq -r '.')
    echo '$response: '; echo $secret_response | jq '.' 

    code=$(echo $secret_response | jq -r ".code")
    echo '$code: ' $code

    api_key_id='5614d362-b552-45f5-bb33-0af13969ce5b' #00484_rie_non_prod_api_key
    app_key_id='20a122da-1b9b-489e-8383-e13c10a97e98' #RIE-SEC-NON-PROD
    API_KEY=$(echo $secret_response | jq ".data[\"api-key\"]")
    APP_KEY=$(echo $secret_response | jq ".data[\"app-key\"]")
    #echo '$API_KEY: ' $API_KEY

    #get API key from datadog
    apikey_response=$(curl -X GET "https://api.datadoghq.com/api/v2/api_keys/${api_key_id}" \
    -H "Accept: application/json" \
    -H "DD-API-KEY: $(echo ${API_KEY} | base64 -d)" \
    -H "DD-APPLICATION-KEY: $(echo ${APP_KEY} | base64 -d)")
    apikey_code=$(echo $apikey_response | jq -r ".code")
    echo '$apikey_code: ' $apikey_code

    if [ $apikey_code -eq 403 ]; then
      echo "API key is invalid or expired."
      exit 1
    fi

    #get APP key from datadog
    appkey_response=$(curl -X GET "https://api.datadoghq.com/api/v2/application_keys/${app_key_id}" \
    -H "Accept: application/json" \
    -H "DD-API-KEY: $(echo ${API_KEY} | base64 -d)" \
    -H "DD-APPLICATION-KEY: $(echo ${APP_KEY} | base64 -d)")
    appkey_code=$(echo $appkey_response | jq -r ".code")
    echo '$appkey_code: ' $appkey_code

    if [ $appkey_code -eq 403 ]; then
      echo "APP key is invalid or expired."
      exit 1
    fi

    payload='{"metadata": {"name": "'${SECRET_NAME}'", "namespace": "'${NAMESPACE}'"}, "data": {"api-key": '${API_KEY}', "app-key": '${APP_KEY}'}}'

    #payload='{"metadata": {"name": "'${SECRET_NAME}'", "namespace": "'${NAMESPACE}'", "annotations": {"kubectl.kubernetes.io/last-applied-configuration":""}}, "data": '"${SECRET_VALUE}"'}'

    echo $payload

    if [ $code -eq 404 ]; then
      echo Creating Secret
      #curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X POST ${APISERVER}/api/v1/namespaces/${NAMESPACE}/secrets \
      -H "Content-Type: application/json" \
      -d "${payload}"
    else
      # Update secret with encoded session token
      echo Updating Secret
      #curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X PUT ${APISERVER}/api/v1/namespaces/${NAMESPACE}/secrets/${SECRET_NAME} \
      #-H "Content-Type: application/json" \
      #-d "${payload}"
    fi
