---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datadog-demo
resources:
  #- namespace.yaml
  #- datadog-operator-helmrelease.yaml
  - datadog-agent.yaml
  - script.yaml
  - sa.yaml
  #- datadog-cjob.yaml
#Customizing patches: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#customizing
patches:
  - path: ./datadog-ds-patch.yaml
  #- target:
  #    kind: Deployment
  #    namespace: datadog-demo
  #  patch: |-
  #    - op: add
  #      path: '/spec/template/metadata/annotations'
  #      value:
  #        reloader.stakater.com/auto: "true"
