---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datadog-demo
labels:
  - pairs:
      agent.datadoghq.com/name: datadog
    includeSelectors: true 
commonAnnotations:
  reloader.stakater.com/auto: "true"
resources:
  #- namespace.yaml
  #- datadog-operator-helmrelease.yaml
  - datadog-agent.yaml
  - script.yaml
  - sa.yaml
  - datadog-job.yaml
  - datadog-cjob.yaml
  #- datadog-patches.yaml
patches:
- path: datadog-patches.yaml
  target:
    kind: DaemonSet
    namespace: datadog-demo
replacements:
- source:
    kind: Job
    namespace: datadog-demo
    fieldPath: metadata.annotations
  targets:
  - select:
      kind: Deployments
      namespace: datadog-demo
    fieldPaths:
    - spec.template.metadata.annotations

#components:
#  - ./components
