apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: datadog-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: datadog-demo
  name: admin-role
rules:
  - apiGroups: [""]
    resources:
      [
        "configmaps",
        "persistentvolumes",
        "persistentvolumeclaims",
        "secrets",
        "services",
      ]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["*"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["*"]
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes"]
    verbs: ["*"]
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ["network-attachment-definitions"]
    verbs: ["*"]
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: datadog-demo
  name: admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-role
subjects:
  - kind: ServiceAccount
    name: demo-admin
    namespace: flux-system
  - kind: ServiceAccount
    name: demo-sa
    namespace: datadog-demo
