---
#source: https://scm.starbucks.com/retail-infrastructure-engineering/taas-flux/blob/main/archive/terraform/base/tf-retail-network/script.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rotate-secret-shell-script
  namespace: datadog-demo
data:
  get-token.sh: |
    #set -x
    apk --no-cache add curl jq

    # Kubernetes API
    APISERVER=https://kubernetes.default.svc
    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
    NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
    TOKEN=$(cat ${SERVICEACCOUNT}/token)
    CACERT=${SERVICEACCOUNT}/ca.crt
    # Datadog api-key & app-key
    SECRET_NAME=datadog-secret

    #response=$(curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/namespaces/${NAMESPACE}/)
    echo curl -s --cacert '"${CACERT}"' --header "Authorization: Bearer '"${TOKEN}"'" -X GET ${APISERVER}/api/v1/ > get_token.sh

    ns_response=$(curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/namespaces/${NAMESPACE}/)
    echo '$ns_response: '; echo $ns_response | jq '.'

    # Retrieve resources from Kubernetes
    response=$(curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/)
    all_response=$(echo $response | jq -r '.')
    #echo '$all_response: '; echo $all_response | jq '.'
    echo '$all_response: '; echo $all_response | jq '.' > all_response

    # Retrieve daemonsets from Kubernetes
    daemonset_response=$(curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/daemonsets/datadog-agent)
    ds_response=$(echo $daemonset_response | jq -r '.')
    echo '$ds_response: '; echo $ds_response | jq '.'

    # Retrieve deployments from Kubernetes
    deployments_response=$(curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/deployments/datadog-cluster-agent)
    dply_response=$(echo $deployments_response | jq -r '.')
    echo '$dply_response: '; echo $dply_response | jq '.'


    sleep 600
