---
apiVersion: batch/v1
kind: Job
metadata:
  name: update-cm-job
  namespace: demo
spec:
  template:
    spec:
      containers:
        - image: alpine
          imagePullPolicy: IfNotPresent
          name: update-cm-job
          #envFrom:
          #  - secretRef:
          #      name: splunk-secrets
          command:
            - /bin/sh
            - -c
            - /shared/modify-webcontent.sh
          volumeMounts:
            - name: script-volume
              mountPath: "/shared/modify-webcontent.sh"
              subPath: modify-webcontent.sh
      serviceAccountName: demo-sa
      volumes:
        - name: script-volume
          configMap:
            name: rotate-configmap-shell-script
            defaultMode: 0777
      restartPolicy: Never
