---
apiVersion: batch/v1
kind: Job
metadata:
  name: get-cm-secret-job
  namespace: demo
spec:
  template:
    spec:
      containers:
      - image: alpine
        imagePullPolicy: IfNotPresent
        name: get-token
        #envFrom:
        #  - secretRef:
        #      name: splunk-secrets
        command:
        - /bin/sh
        - -c
        - /shared/modify-webcontent.sh
        volumeMounts:
          - name: get-token-volume
            mountPath: "/shared/modify-webcontent.sh"
            subPath: modify-webcontent.sh
      serviceAccountName: demo-sa
      volumes:
        - name: get-token-volume
          configMap:
            name: rotate-secret-shell-script
            defaultMode: 0777
      restartPolicy: Never
