namespace: demo
resources:
  - namespace.yaml
  - deployment.yaml
  - init-cm.yaml
  - sa.yaml
  - script.yaml
  - cm-job.yaml
  - cm-cronjob.yaml
  #- pvc.yaml

# This is used to generate a Secret for the reloader-demo app
secretGenerator:
  - name: nginx-secret-config
    files:
      - nginx-custom-config.conf
    type: Opaque
generatorOptions:
  disableNameSuffixHash: true
