---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rotate-configmap-shell-script
  namespace: demo
data:
  modify-webcontent.sh: |
    #!/bin/sh
    #set -x
    apk --no-cache add curl jq

    # Execute the Bash script embedded as a heredoc
    function delay_script() {
      COUNTER=3 # 180 = 3 minutes in seconds
      COUNTER=$(( $COUNTER * 60 ))

      echo "Starting break for $COUNTER seconds ..."

      while [ $COUNTER -gt 0 ]
      do
        echo $COUNTER seconds remaining in break
        COUNTER=$(( COUNTER - 1 ))
        sleep 1
      done
    }

    echo "Waiting for 3 minutes before running the script ..."
    echo "Start time: " $(date)
    #delay_script
    echo "End time: " $(date)

    # Kubernetes API
    APISERVER=https://kubernetes.default.svc
    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
    NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
    TOKEN=$(cat ${SERVICEACCOUNT}/token)
    CACERT=${SERVICEACCOUNT}/ca.crt

    # ConfigMap
    CM_NAME=webcontent-cm

    export cm_response=$(curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps/${CM_NAME})

    cm_code=$(echo $cm_response | jq -r ".code")

    echo $cm_response  | jq -r "."

    echo Setting configMap metadata to vars ...
    metadata=$(echo $cm_response | jq '.metadata')
    managedFields=$(echo $metadata | jq -r '.managedFields')
    createdTime=$(echo $metadata | jq -r '.creationTimestamp')
    updatedTime=$(echo $metadata | jq -r '.managedFields[0].time')
    echo '$createdTime:' $createdTime
    echo '$updatedTime:' $updatedTime
    echo Setting configMap metadata to vars END...:

    echo "Adding createdTime and updatedTime to HTML file ..."
    temp_file=$(mktemp)
    echo $cm_response | jq -r '.data' > $temp_file
    sed -i 's/timeUpdatedValue\\">[^<]*</timeUpdatedValue\\">'"$updatedTime"'</g' $temp_file
    sed -i 's/timeCreatedValue\\">[^<]*</timeCreatedValue\\">'"$createdTime"'</g' $temp_file
    new_cm=$(cat $temp_file)

    if $(echo $new_cm | grep 'timeUpdatedValue\\">') &> /dev/null;then 
      echo "hello.html timeUpdatedValue was not populated" >&2
      exit 1
    else
      echo $new_cm | grep 'timeUpdatedValue'
    fi

    cm_payload='{"metadata": {"name": "'${CM_NAME}'", "namespace": "'${NAMESPACE}'", "managedFields": '"${managedFields}"'}, "data": '"${new_cm}"'}'

    function create_configmap() {
      echo Creating ConfigMap: ${CM_NAME}
      curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X POST ${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps \
      -H "Content-Type: application/json" \
      -d "${1}"
    }

    function update_configmap() {
      # Update ConfigMap with encoded session token
      echo Updating ConfigMap: ${CM_NAME}
      echo ${CM_NAME} ... "${cm_payload}"
      curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X PUT ${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps/${CM_NAME} \
      -H "Content-Type: application/json" \
      -d "${cm_payload}"
    }

    if [ $cm_code -eq 404 ]; then
      payload='{"metadata": {"name": "'${CM_NAME}'", "namespace": "'${NAMESPACE}'"}, "data": {"welcome.html": "Hello World!", "hello.html": "Hello ISK!"}}'
      create_configmap "${payload}"
    else
      update_configmap
    fi
