---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rotate-secret-shell-script
  namespace: demo
data:
  modify-webcontent.sh: |
    apk --no-cache add curl jq

    # Kubernetes API
    APISERVER=https://kubernetes.default.svc
    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
    NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
    TOKEN=$(cat ${SERVICEACCOUNT}/token)
    CACERT=${SERVICEACCOUNT}/ca.crt

    # ConfigMap
    CM_NAME=webcontent-cm

    export cm_response=$(curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps/${CM_NAME})

    cm_code=$(echo $cm_response | jq -r ".code")

    echo '$cm_response' keys ...:
    echo $cm_response | jq -r '. | keys'

    echo '$cm_response' metadata START...:
    metadata=$(echo $cm_response | jq '.metadata')
    createdTime=$(echo $metadata | jq -r '.creationTimestamp')
    updatedTime=$(echo $metadata | jq -r '.managedFields[0].time')
    echo '$cm_response' metadata END...:

    echo '$cm_response'.data START...:
    cm_data=$(echo $cm_response | jq -r '.data')
    cm_hello=$(echo $cm_data | jq -r '.["hello.html"]')
    cm_welcome=$(echo $cm_data | jq -r '.["welcome.html"]')
    echo '$cm_response'.data END...:

    cm_payload='{"metadata": {"name": "'${CM_NAME}'", "namespace": "'${NAMESPACE}'"}, "data": {"hello.html": "'${cm_hello}'", "welcome.html": "'${cm_welcome}'"}}'

    #echo $cm_payload

    if [ $cm_code -eq 404 ]; then
      echo Creating ConfigMap: ${CM_NAME}
      curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X POST ${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps \
      -H "Content-Type: application/json" \
      -d "${cm_payload}"
    fi

    function update_configmap() {
      # Update ConfigMap with encoded session token
      echo Updating ConfigMap: ${CM_NAME}
      echo ${CM_NAME} ... "${cm_payload}"
      curl -s --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X PUT ${APISERVER}/api/v1/namespaces/${NAMESPACE}/configmaps/${CM_NAME} \
      -H "Content-Type: application/json" \
      -d "${cm_payload}"
    }
