apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: datavol-example
  namespace: cron-test
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 512Mi
    storageClassName: local-path
  source:
    http:
      url: https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86_64/alpine-standard-3.18.0-x86_64.iso